a=str(input('introdu primul cuvant: '))
b=str(input('introdu al doilea cuvant: '))
c=str(input('introdu al treilea cuvant: '))
d=str(input('introdu al patrulea cuvant: '))
print(a)
print(b)
print(c)
print(d)
print(a+" "+b+" "+c+" "+d+".")